server {
    listen 80 default_server;
    server_name _;

    return 444;
}

server {
    listen 80;
    server_name db-inv.bnkc.com;

    client_max_body_size 20m;

    location / {
        return 301 https://db-inv.bnkc.com$request_uri;
    }
}
